name: build

on: [push, pull_request]

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  jvm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 18

      - uses: gradle/gradle-build-action@v2

      - name: Test
        run: ./gradlew build

  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'hrafnthor/retrofit-result-adapter'
    needs:
      - jvm
      
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 18

      - uses: gradle/gradle-build-action@v2

      - name: Sign and upload artifacts
        run: ./gradlew listPropertiesAndPublish
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.PGP_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.PGP_SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.PGP_SIGNING_KEY_PASSWORD }}
