name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  jvm:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

        # The repository should not have any wrappers present but if it does then
        # this setp will figure out if they match official sha256 checksums
      - name: Validate any Gradle wrappers
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Java environment
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 18

      - name: Setup Gradle environment
        uses: gradle/gradle-build-action@v2

      - name: Generate Gradle wrapper
        run: gradle wrapper

      - name: Test
        run: ./gradlew build

  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'hrafnthor/retrofit-result-adapter' && github.ref == 'refs/heads/main'
    needs:
      - jvm
      
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 18

      - uses: gradle/gradle-build-action@v2

      - name: Sign and upload artifacts
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.PGP_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.PGP_SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.PGP_SIGNING_KEY_PASSWORD }}
